### ISSUE TITLE
Video creation failed for unknown reason

### ISSUE THREAD

**Issue by invisibleroads** [kashfifahim/CC_images_to_video#16]
```
Traceback (most recent call last):
  File "/home/user/experiments/crosscompute-examples/CC_images_to_video/run.py", line 59, in <module>
    images_to_video(image_paths, str(temp_video_file), fps=30, duration=user_defined_duration)
  File "/home/user/experiments/crosscompute-examples/CC_images_to_video/image_processing.py", line 158, in images_to_video
    resized_img = resize_image(img, target_width, target_height)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/experiments/crosscompute-examples/CC_images_to_video/image_processing.py", line 126, in resize_image
    return cv2.copyMakeBorder(resized_image, top_padding, bottom_padding, left_padding, right_padding, cv2.BORDER_CONSTANT, value=[0, 0, 0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.8.1) /io/opencv/modules/core/src/copy.cpp:1026: error: (-215:Assertion failed) top >= 0 && bottom >= 0 && left >= 0 && right >= 0 && _src.dims() <= 2 in function 'copyMakeBorder'
```

[Screenshot from 2023-12-06 15-.zip](https://github.com/kashfifahim/CC_images_to_video/files/13620552/Screenshot.from.2023-12-06.15-.zip)

**Comment by invisibleroads** [comment]
For this case, the source images have different widths and heights from each other. This might be related to the error.

**Comment by kashfifahim** [comment]
Error stemmed from cv library trying to add borders to image with negative padding.  
Implemented checks to ensure resizing function passes images with 0 or positive padding.
